using Test
using TwoTimescaleResilience

@testset "TwoTimescaleResilience Tests" begin
    include("test_deb_axes.jl")
    include("test_deb_axes_grid.jl")
    include("test_default_mappings.jl")
    include("test_deb_pipeline.jl")
    include("test_pulse_deb_axes.jl")
    include("test_deb_axis_response.jl")
    include("test_examples.jl")
    include("test_background.jl")
    include("test_multistressor.jl")
    include("test_grids.jl")
    include("test_pulses.jl")
    include("test_simulation.jl")
    include("test_metrics.jl")
    include("test_plotting.jl")
    include("test_ascii.jl")
    include("test_synthetic_raster.jl")
    include("test_netcdf.jl")

    include("test_recovery_penalty.jl")
    include("test_condition_buffer.jl")
    include("test_reduced_deb_response.jl")
    include("test_mode_of_action.jl")
    include("test_default_isimip_moa.jl")
    include("test_exposure_filters.jl")
    include("test_moa_deb_mapping.jl")
    include("test_isimip_deb_pipeline.jl")
    include("test_species_profiles.jl")
    include("test_isimip_event_response.jl")
    include("test_examples_isimip_moa.jl")
    include("test_deb_pipeline_recovery_math.jl")

    include("test_ecotox.jl")
    include("test_ecotox_library.jl")
    include("test_amp_library.jl")
    include("test_amp_species_profile.jl")
    include("test_amp_pipeline_integration.jl")
end
