# Extract a station-level Stress-on-Stress (survival-in-air) margin-validation table from the
# ICES DOME 2024 OSPAR CEMP biota data. Base Julia only (no project deps) -> run as:
#   julia +release scripts/extract_dome_sos.jl
# Reads the gitignored raw download data/external/ospar_cemp2024_biota_data.csv (re-fetch:
# figshare 27211422, file 49767237, CC BY 4.0) and writes the committed derived table
# data/external/sos_dome_ukcemp.csv (one row per station: median SoS survival + median
# co-located tissue contaminants + station-typical body size).
#
# SoS (determinand SURVT, unit "d") = survival-in-air days; higher = healthier (more
# resilient to the acute emersion/anoxia challenge). All Mytilus edulis, 18 UK stations,
# 2012-2022. Contaminants/size are station medians over all M. edulis rows (years pooled);
# this is a station-level cross-sectional summary (station-typical pressure vs survival).

using Statistics

const RAW = joinpath(@__DIR__, "..", "data", "external", "ospar_cemp2024_biota_data.csv")
const OUT = joinpath(@__DIR__, "..", "data", "external", "sos_dome_ukcemp.csv")

# quote-aware CSV line split (station names may contain commas inside quotes)
function splitcsv(line)
    out = String[]; buf = IOBuffer(); inq = false
    for c in line
        if c == '"'; inq = !inq
        elseif c == ',' && !inq; push!(out, String(take!(buf)))
        else; print(buf, c); end
    end
    push!(out, String(take!(buf)))
    return out
end
unq(s) = strip(s, ['"', ' '])
num(s) = (s = unq(s); (isempty(s)) ? NaN : something(tryparse(Float64, s), NaN))

# column indices (1-based) in biota_data.csv
const C_STATION = 5; const C_NAME = 6; const C_LAT = 8; const C_YEAR = 12
const C_SPECIES = 17; const C_DET = 22; const C_CONC = 26; const C_LNMEA = 29; const C_DRYWT = 30

# determinands to capture (others ignored)
const METALS   = ["CD", "CU", "HG", "PB", "ZN"]
const PAH23    = ["NAP", "ACNLE", "ACNE", "FLE", "PA", "ANT"]   # 2-3 ring toxic hydrocarbons
const PCB      = ["SCB7", "CB28", "CB52", "CB101", "CB118", "CB138", "CB153", "CB180"]
const CAPTURE  = Set(vcat(["SURVT"], METALS, PAH23, PCB))

# accumulators: station => determinand => [values]; station => :LNMEA/:DRYWT => [values]
vals = Dict{String, Dict{String, Vector{Float64}}}()
meta = Dict{String, Tuple{String, Float64}}()   # station => (name, latitude)

# pass 1: find the 18 SURVT stations
survt_stations = Set{String}()
open(RAW) do io
    readline(io)  # header
    for line in eachline(io)
        f = splitcsv(line); length(f) < C_DRYWT && continue
        unq(f[C_DET]) == "SURVT" && push!(survt_stations, unq(f[C_STATION]))
    end
end
println("SURVT stations: ", length(survt_stations))

# pass 2: accumulate SoS + contaminants + size for those stations (M. edulis only)
open(RAW) do io
    readline(io)
    for line in eachline(io)
        f = splitcsv(line); length(f) < C_DRYWT && continue
        st = unq(f[C_STATION]); (st in survt_stations) || continue
        unq(f[C_SPECIES]) == "Mytilus edulis" || continue
        d = get!(vals, st, Dict{String, Vector{Float64}}())
        if !haskey(meta, st); meta[st] = (unq(f[C_NAME]), num(f[C_LAT])); end
        det = unq(f[C_DET])
        if det in CAPTURE
            v = num(f[C_CONC]); isfinite(v) && push!(get!(d, det, Float64[]), v)
        end
        l = num(f[C_LNMEA]); isfinite(l) && push!(get!(d, "LNMEA", Float64[]), l)
        w = num(f[C_DRYWT]); isfinite(w) && push!(get!(d, "DRYWT", Float64[]), w)
    end
end

med(d, k) = (haskey(d, k) && !isempty(d[k])) ? median(d[k]) : NaN
fmt(x) = isfinite(x) ? string(round(x, sigdigits = 5)) : "nd"

cols = vcat(["station_code", "station_name", "latitude", "survt_n", "survt_median_d",
             "LNMEA", "DRYWT"], METALS, PAH23, ["SCB7"])
open(OUT, "w") do io
    println(io, "# Station-level Stress-on-Stress (survival-in-air) + co-located tissue")
    println(io, "# contaminants, Mytilus edulis, ICES DOME 2024 OSPAR CEMP (UK, 2012-2022).")
    println(io, "# Generated by scripts/extract_dome_sos.jl from the gitignored raw DOME biota")
    println(io, "# data (figshare 27211422, CC BY 4.0). survt_median_d = median survival-in-air")
    println(io, "# days (higher = more resilient). Contaminants/size = station medians (ug/kg DW;")
    println(io, "# LNMEA mm; DRYWT %), years pooled. SCB7 = sum-7 PCB (median of reported SCB7,")
    println(io, "# else sum of the 7 ICES congener medians). No organotins at these stations.")
    println(io, join(cols, ","))
    for st in sort(collect(survt_stations))
        d = get(vals, st, Dict{String, Vector{Float64}}())
        name, lat = get(meta, st, ("", NaN))
        survn = haskey(d, "SURVT") ? length(d["SURVT"]) : 0
        # PCB: prefer reported SCB7, else sum the 7 congener station-medians
        scb7 = med(d, "SCB7")
        if !isfinite(scb7)
            cong = [med(d, c) for c in ["CB28","CB52","CB101","CB118","CB138","CB153","CB180"]]
            scb7 = all(isfinite, cong) ? sum(cong) : NaN
        end
        row = vcat([st, "\"$name\"", fmt(lat), string(survn), fmt(med(d, "SURVT")),
                    fmt(med(d, "LNMEA")), fmt(med(d, "DRYWT"))],
                   [fmt(med(d, m)) for m in METALS],
                   [fmt(med(d, p)) for p in PAH23],
                   [fmt(scb7)])
        println(io, join(row, ","))
    end
end
println("wrote ", OUT)
# quick echo
for line in eachline(OUT); startswith(line, "#") || println(line); end
